### ISSUE TITLE
Screenshot for section 2.1 in README

### ISSUE THREAD

**Issue by rgerkin** [openworm/muscle_model#26]
Could someone post a screenshot of the jNeuroML output window (the voltage trace) at the end of section 2.1 of the README?  I have an output which is... boring, and I think probably not right.

**Comment by pgleeson** [comment]
Here you go:
![selection_157](https://cloud.githubusercontent.com/assets/1556687/5816018/6f954a46-a093-11e4-99c1-fb50962a3ed2.png)

Note that this is after resizing some windows and selecting View -> Frame in the menus

Left top: conductances through channels at a series of voltage clamp holding potentials, generally showing the rapid opening & slow closing due to inactivation
Left bottom: currents through channel when reversal potential is set to -55mV

Middle top: membrane potential for the series of voltage clamp steps
Middle bottom 2 traces: tau for activation (p) & inactivation (q) - no voltage dependence & p<<q

Right traces: activation variable (p, top) i.e. with greater depolarisation there is a greater chance of the gate opening; inactivation variable (q, bottom) i.e. with greater depolarisation there is a lower chance of the gate opening; conductance of channel proportional to p^4 * q

(intro to channel modelling not for your benefit of course @rgerkin...)

**Comment by rgerkin** [comment]
OK, good, those are what I what I am getting.  I said "boring" before because I was looking at the unchanging gating variables but didn't see that the voltage was clamped.  Thanks.
