### ISSUE TITLE
Digitize the figure mentioned in #31

### ISSUE THREAD

**Issue by travs** [openworm/muscle_model#40]
A [walkthrough of digitizing is online.](https://channelworm.readthedocs.org/en/latest/digitization/#walkthrough-of-the-process) 

The figure is in #31 -- it can also be extracted again from the original paper, which is linked there.

**Comment by rayner** [comment]
Done. Sanity checks would be appreciated. My method was:

1. View original paper in PDF format at 400% magnification.
2. Take a screenshot of Figure 1A (in PNG format).
3. Edit the image to superimpose the scale onto the two parts of the figure. This was done so that the "known points" for the WebPlotDigitizer app could be set in sensible places (starting at zero current, and with the onset of the pulse at zero seconds).
4. Digitize each part of the figure as described in the walkthrough. The figure doesn't have the original data points marked, so I placed points in the salient features of the trace (start, end, pulse onset, peak, and along the decay curves).

Links to digitized data on Plotly:
https://plot.ly/~rayner/6
https://plot.ly/~rayner/11

Attached:
Screenshot of figure 1A (step 2 above).
Edited screenshot with scale superimposed (step 3 above).

![1a](https://cloud.githubusercontent.com/assets/881058/8275167/139169fa-1898-11e5-8d8d-cbf552601012.png)
![1a-edited](https://cloud.githubusercontent.com/assets/881058/8275168/13aa16f8-1898-11e5-8514-026db94e970b.png)

**Comment by travs** [comment]
@rayner 

Great! Thank you!
I've compared your plots with the literature graphs and they do indeed appear sane :smile: 

Superimposing the axis onto the plot was a good call, as well as using the key features of a graph since no original data points were available.

This allows for #41 and #42 to happen when #31 is resolved.

**Comment by travs** [comment]
[The current milestone](https://waffle.io/VahidGh/ChannelWorm?milestone=Create%20unit%20test%20on%20the%20full%20muscle%20model%20that%20reproduces%20Figure%201A%20from%20Liu,%20Hollopeter,%20%26%20Jorgensen%202009) is actually blocked by #31. 

Is #31 something you would be interested in trying, @rayner ? Or is there something else you find more interesting?

**Comment by rayner** [comment]
Thanks for the review, much appreciated. #31 looks like something I could contribute to. I'll set aside some time to work on it over the weekend.

**Comment by travs** [comment]
@rayner 
Hey Rayner, did you get a chance to look at #31 over the weekend?

**Comment by rayner** [comment]
A bit, yes. I've got the latest version of the muscle model now, and have been figuring out how to approach this using a LEMS model. It looks like we need something similar to the voltage clamp simulation defined in LEMS_Figure2B.xml, but with the addition of needing to account for the light-sensitive channels. I should be able to work on it a bit more tomorrow.

**Comment by travs** [comment]
Ok, since you're started on it I've "assigned" you to #31, Rayner. Let me know over there if there's anything I can do to help!
